### ISSUE TITLE
Please help，OSError: [WinError 127] The specified program could not be found

### ISSUE THREAD

**Issue by gmf1982** [RichardErkhov/Richard-roop#17]
(venv) D:\deepface\Richard-roop>python run.py --gpu --gpu-threads 1
Traceback (most recent call last):
  File "D:\deepface\Richard-roop\run.py", line 3, in <module>
    from roop import core
  File "D:\deepface\Richard-roop\roop\core.py", line 11, in <module>
    import torch
  File "D:\deepface\Richard-roop\venv\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\deepface\Richard-roop\venv\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

(venv) D:\deepface\Richard-roop>python run.py
Traceback (most recent call last):
  File "D:\deepface\Richard-roop\run.py", line 3, in <module>
    from roop import core
  File "D:\deepface\Richard-roop\roop\core.py", line 11, in <module>
    import torch
  File "D:\deepface\Richard-roop\venv\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\deepface\Richard-roop\venv\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

**Comment by RichardErkhov** [comment]
What's the cuda version ? Is it in the path ? Did you install cudnn ?

**Comment by gmf1982** [comment]
> cuda版本是什么？它在路径中吗？你安装了 cudnn 吗？

Yes, cudnn has been installed, and the cuda version is 11.7
![image](https://github.com/RichardErkhov/Richard-roop/assets/130820234/5e19db61-16a4-43cf-a51a-76f64a4e8423)
![image](https://github.com/RichardErkhov/Richard-roop/assets/130820234/7e07acf3-050b-44f4-a0c3-512aede42f80)

**Comment by RichardErkhov** [comment]
you didn't add it right, you have to put it without \bin at the end

**Comment by RichardErkhov** [comment]
![image](https://github.com/RichardErkhov/Richard-roop/assets/104026872/c2c54576-d691-4537-9a4b-7761c802645d)

**Comment by gmf1982** [comment]
> you didn't add it right, you have to put it without \bin at the end
I modified the path according to your method, but it still doesn't work

![image](https://github.com/RichardErkhov/Richard-roop/assets/130820234/9a22fad4-8c2e-4d26-85a5-e2b7887ea47e)

![image](https://github.com/RichardErkhov/Richard-roop/assets/130820234/ce099a05-977d-4108-91d7-122d8c618393)

**Comment by RichardErkhov** [comment]
how did you install torch ?

**Comment by gmf1982** [comment]
> 你是如何安装火炬的？
I use the command line to install torch, do I need to use Anaconda to install it?

![image](https://github.com/RichardErkhov/Richard-roop/assets/130820234/e38b06fc-7e00-4555-8be3-c60f663e5862)

**Comment by RichardErkhov** [comment]
ok, so what I can understand from the error that something from cuda/cudnn is missing. First of all try reinstalling roop, and if it doesn't help, I think you might need to reinstall cuda and cudnn

**Comment by gmf1982** [comment]
> 好的，所以我可以从错误中了解到 cuda/cudnn 中的某些内容丢失了。首先尝试重新安装roop，如果没有帮助，我想你可能需要重新安装cuda和cudnn

ok, thanks for your help！

**Comment by gmf1982** [comment]
I finally solved this problem, it turned out that it was caused by copying venv directly from another roop folder that was already installed. Solved after creating a new venv.

**Comment by RichardErkhov** [comment]
haha, you can't just move the venv, you need to create a new one =)
